/* eslint-disable */
// @ts-nocheck
/**
 * virtual-world by Radu Mariescu-Istodor (https://github.com/gniziemazity/virtual-world), MIT License.
 * Generated by scripts/build-vw.mjs from phase "11. MiniMap" — do not edit by hand.
 *
 * The editors reference a page-global `world`; the host sets it with setEditorWorld().
 */
let world = null;
export function setEditorWorld(w) { world = w; }
// ───── world/js/primitives/point.js ─────
class Point {
   constructor(x, y) {
      this.x = x;
      this.y = y;
   }

   equals(point) {
      return this.x == point.x && this.y == point.y;
   }

   draw(ctx, { size = 18, color = "black", outline = false, fill = false } = {}) {
      const rad = size / 2;
      ctx.beginPath();
      ctx.fillStyle = color;
      ctx.arc(this.x, this.y, rad, 0, Math.PI * 2);
      ctx.fill();
      if (outline) {
         ctx.beginPath();
         ctx.lineWidth = 2;
         ctx.strokeStyle = "yellow";
         ctx.arc(this.x, this.y, rad * 0.6, 0, Math.PI * 2);
         ctx.stroke();
      }
      if (fill) {
         ctx.beginPath();
         ctx.arc(this.x, this.y, rad * 0.4, 0, Math.PI * 2);
         ctx.fillStyle = "yellow";
         ctx.fill();
      }
   }
}

// ───── world/js/primitives/segment.js ─────
class Segment {
   constructor(p1, p2, oneWay = false) {
      this.p1 = p1;
      this.p2 = p2;
      this.oneWay = oneWay;
   }

   length() {
      return distance(this.p1, this.p2);
   }

   directionVector() {
      return normalize(subtract(this.p2, this.p1));
   }

   equals(seg) {
      return this.includes(seg.p1) && this.includes(seg.p2);
   }

   includes(point) {
      return this.p1.equals(point) || this.p2.equals(point);
   }

   distanceToPoint(point) {
      const proj = this.projectPoint(point);
      if (proj.offset > 0 && proj.offset < 1) {
         return distance(point, proj.point);
      }
      const distToP1 = distance(point, this.p1);
      const distToP2 = distance(point, this.p2);
      return Math.min(distToP1, distToP2);
   }

   projectPoint(point) {
      const a = subtract(point, this.p1);
      const b = subtract(this.p2, this.p1);
      const normB = normalize(b);
      const scaler = dot(a, normB);
      const proj = {
         point: add(this.p1, scale(normB, scaler)),
         offset: scaler / magnitude(b),
      };
      return proj;
   }

   draw(ctx, { width = 2, color = "black", dash = [], cap = "butt" } = {}) {
      ctx.beginPath();
      ctx.lineWidth = width;
      ctx.strokeStyle = color;
      ctx.lineCap = cap;
      if (this.oneWay) {
         dash = [4, 4];
      }
      ctx.setLineDash(dash);
      ctx.moveTo(this.p1.x, this.p1.y);
      ctx.lineTo(this.p2.x, this.p2.y);
      ctx.stroke();
      ctx.setLineDash([]);
   }
}

// ───── world/js/primitives/polygon.js ─────
class Polygon {
   constructor(points) {
      this.points = points;
      this.segments = [];
      for (let i = 1; i <= points.length; i++) {
         this.segments.push(
            new Segment(points[i - 1], points[i % points.length])
         );
      }
   }

   static load(info) {
      return new Polygon(
         info.points.map((i) => new Point(i.x, i.y))
      );
   }

   static union(polys) {
      Polygon.multiBreak(polys);
      const keptSegments = [];
      for (let i = 0; i < polys.length; i++) {
         for (const seg of polys[i].segments) {
            let keep = true;
            for (let j = 0; j < polys.length; j++) {
               if (i != j) {
                  if (polys[j].containsSegment(seg)) {
                     keep = false;
                     break;
                  }
               }
            }
            if (keep) {
               keptSegments.push(seg);
            }
         }
      }
      return keptSegments;
   }

   static multiBreak(polys) {
      for (let i = 0; i < polys.length - 1; i++) {
         for (let j = i + 1; j < polys.length; j++) {
            Polygon.break(polys[i], polys[j]);
         }
      }
   }

   static break(poly1, poly2) {
      const segs1 = poly1.segments;
      const segs2 = poly2.segments;
      for (let i = 0; i < segs1.length; i++) {
         for (let j = 0; j < segs2.length; j++) {
            const int = getIntersection(
               segs1[i].p1,
               segs1[i].p2,
               segs2[j].p1,
               segs2[j].p2
            );

            if (int && int.offset != 1 && int.offset != 0) {
               const point = new Point(int.x, int.y);
               let aux = segs1[i].p2;
               segs1[i].p2 = point;
               segs1.splice(i + 1, 0, new Segment(point, aux));
               aux = segs2[j].p2;
               segs2[j].p2 = point;
               segs2.splice(j + 1, 0, new Segment(point, aux));
            }
         }
      }
   }

   distanceToPoint(point) {
      return Math.min(...this.segments.map((s) => s.distanceToPoint(point)));
   }

   distanceToPoly(poly) {
      return Math.min(...this.points.map((p) => poly.distanceToPoint(p)));
   }

   intersectsPoly(poly) {
      for (let s1 of this.segments) {
         for (let s2 of poly.segments) {
            if (getIntersection(s1.p1, s1.p2, s2.p1, s2.p2)) {
               return true;
            }
         }
      }
      return false;
   }

   containsSegment(seg) {
      const midpoint = average(seg.p1, seg.p2);
      return this.containsPoint(midpoint);
   }

   containsPoint(point) {
      const outerPoint = new Point(-1000, -1000);
      let intersectionCount = 0;
      for (const seg of this.segments) {
         const int = getIntersection(outerPoint, point, seg.p1, seg.p2);
         if(int){
            intersectionCount++;
         }
      }
      return intersectionCount % 2 == 1;
   }

   drawSegments(ctx) {
      for (const seg of this.segments) {
         seg.draw(ctx, { color: getRandomColor(), width: 5 });
      }
   }

   draw(
      ctx,
      { stroke = "blue", lineWidth = 2, fill = "rgba(0,0,255,0.3)", join = "miter" } = {}
   ) {
      ctx.beginPath();
      ctx.fillStyle = fill;
      ctx.strokeStyle = stroke;
      ctx.lineWidth = lineWidth;
      ctx.lineJoin = join;
      ctx.moveTo(this.points[0].x, this.points[0].y);
      for (let i = 1; i < this.points.length; i++) {
         ctx.lineTo(this.points[i].x, this.points[i].y);
      }
      ctx.closePath();
      ctx.fill();
      ctx.stroke();
   }
}

// ───── world/js/primitives/envelope.js ─────
class Envelope {
   constructor(skeleton, width, roundness = 1) {
      if (skeleton) {
         this.skeleton = skeleton;
         this.poly = this.#generatePolygon(width, roundness);
      }
   }

   static load(info) {
      const env = new Envelope();
      env.skeleton = new Segment(info.skeleton.p1, info.skeleton.p2);
      env.poly = Polygon.load(info.poly);
      return env;
   }

   #generatePolygon(width, roundness) {
      const { p1, p2 } = this.skeleton;

      const radius = width / 2;
      const alpha = angle(subtract(p1, p2));
      const alpha_cw = alpha + Math.PI / 2;
      const alpha_ccw = alpha - Math.PI / 2;
      
      const points = [];
      const step = Math.PI / Math.max(1, roundness);
      const eps = step / 2;
      for (let i = alpha_ccw; i <= alpha_cw + eps; i += step) {
         points.push(translate(p1, i, radius));
      }
      for (let i = alpha_ccw; i <= alpha_cw + eps; i += step) {
         points.push(translate(p2, Math.PI + i, radius));
      }

      return new Polygon(points);
   }

   draw(ctx, options) {
      this.poly.draw(ctx, options);
   }
}

// ───── world/js/math/utils.js ─────
function getNearestPoint(loc, points, threshold = Number.MAX_SAFE_INTEGER) {
   let minDist = Number.MAX_SAFE_INTEGER;
   let nearest = null;
   for (const point of points) {
      const dist = distance(point, loc);
      if (dist < minDist && dist < threshold) {
         minDist = dist;
         nearest = point;
      }
   }
   return nearest;
}

function getNearestSegment(loc, segments, threshold = Number.MAX_SAFE_INTEGER) {
   let minDist = Number.MAX_SAFE_INTEGER;
   let nearest = null;
   for (const seg of segments) {
      const dist = seg.distanceToPoint(loc);
      if (dist < minDist && dist < threshold) {
         minDist = dist;
         nearest = seg;
      }
   }
   return nearest;
}

function distance(p1, p2) {
   return Math.hypot(p1.x - p2.x, p1.y - p2.y);
}

function average(p1, p2) {
   return new Point((p1.x + p2.x) / 2, (p1.y + p2.y) / 2);
}

function dot(p1, p2) {
   return p1.x * p2.x + p1.y * p2.y;
}

function add(p1, p2) {
   return new Point(p1.x + p2.x, p1.y + p2.y);
}

function subtract(p1, p2) {
   return new Point(p1.x - p2.x, p1.y - p2.y);
}

function scale(p, scaler) {
   return new Point(p.x * scaler, p.y * scaler);
}

function normalize(p) {
   return scale(p, 1 / magnitude(p));
}

function magnitude(p) {
   return Math.hypot(p.x, p.y);
}

function perpendicular(p) {
   return new Point(-p.y, p.x);
}

function translate(loc, angle, offset) {
   return new Point(
      loc.x + Math.cos(angle) * offset,
      loc.y + Math.sin(angle) * offset
   );
}

function angle(p) {
   return Math.atan2(p.y, p.x);
}

function getIntersection(A, B, C, D) {
   const tTop = (D.x - C.x) * (A.y - C.y) - (D.y - C.y) * (A.x - C.x);
   const uTop = (C.y - A.y) * (A.x - B.x) - (C.x - A.x) * (A.y - B.y);
   const bottom = (D.y - C.y) * (B.x - A.x) - (D.x - C.x) * (B.y - A.y);

   const eps = 0.001;
   if (Math.abs(bottom) > eps) {
      const t = tTop / bottom;
      const u = uTop / bottom;
      if (t >= 0 && t <= 1 && u >= 0 && u <= 1) {
         return {
            x: lerp(A.x, B.x, t),
            y: lerp(A.y, B.y, t),
            offset: t,
         };
      }
   }

   return null;
}

function lerp(a, b, t) {
   return a + (b - a) * t;
}

function lerp2D(A, B, t) {
   return new Point(lerp(A.x, B.x, t), lerp(A.y, B.y, t));
}

function invLerp(a, b, v) {
   return (v - a) / (b - a);
}

function degToRad(degree) {
   return degree * Math.PI / 180;
}

function getRandomColor() {
   const hue = 290 + Math.random() * 260;
   return "hsl(" + hue + ", 100%, 60%)";
}

function getFake3dPoint(point, viewPoint, height) {
   const dir = normalize(subtract(point, viewPoint));
   const dist = distance(point, viewPoint);
   const scaler = Math.atan(dist / 300) / (Math.PI / 2);
   return add(point, scale(dir, height * scaler));
}

// ───── utils.js ─────
/* duplicate lerp omitted */

/* duplicate getIntersection omitted */

function polysIntersect(poly1, poly2){
    for(let i=0;i<poly1.length;i++){
        for(let j=0;j<poly2.length;j++){
            const touch=getIntersection(
                poly1[i],
                poly1[(i+1)%poly1.length],
                poly2[j],
                poly2[(j+1)%poly2.length]
            );
            if(touch){
                return true;
            }
        }
    }
    return false;
}

function getRGBA(value){
    const alpha=Math.abs(value);
    const R=value<0?0:255;
    const G=R;
    const B=value>0?0:255;
    return "rgba("+R+","+G+","+B+","+alpha+")";
}

/* duplicate getRandomColor omitted */

// ───── world/js/math/graph.js ─────
class Graph {
   constructor(points = [], segments = []) {
      this.points = points;
      this.segments = segments;
   }

   static load(info) {
      const points = info.points.map((i) => new Point(i.x, i.y));
      const segments = info.segments.map((i) => new Segment(
         points.find((p) => p.equals(i.p1)),
         points.find((p) => p.equals(i.p2))
      ));
      return new Graph(points, segments);
   }

   hash() {
      return JSON.stringify(this);
   }

   addPoint(point) {
      this.points.push(point);
   }

   containsPoint(point) {
      return this.points.find((p) => p.equals(point));
   }

   tryAddPoint(point) {
      if (!this.containsPoint(point)) {
         this.addPoint(point);
         return true;
      }
      return false;
   }

   removePoint(point) {
      const segs = this.getSegmentsWithPoint(point);
      for (const seg of segs) {
         this.removeSegment(seg);
      }
      this.points.splice(this.points.indexOf(point), 1);
   }

   addSegment(seg) {
      this.segments.push(seg);
   }

   containsSegment(seg) {
      return this.segments.find((s) => s.equals(seg));
   }

   tryAddSegment(seg) {
      if (!this.containsSegment(seg) && !seg.p1.equals(seg.p2)) {
         this.addSegment(seg);
         return true;
      }
      return false;
   }

   removeSegment(seg) {
      this.segments.splice(this.segments.indexOf(seg), 1);
   }

   getSegmentsWithPoint(point) {
      const segs = [];
      for (const seg of this.segments) {
         if (seg.includes(point)) {
            segs.push(seg);
         }
      }
      return segs;
   }

   dispose() {
      this.points.length = 0;
      this.segments.length = 0;
   }

   draw(ctx) {
      for (const seg of this.segments) {
         seg.draw(ctx);
      }

      for (const point of this.points) {
         point.draw(ctx);
      }
   }
}

// ───── world/js/math/osm.js ─────
const Osm = {
   parseRoads: (data) => {
      const nodes = data.elements.filter((n) => n.type == "node");
      
      const lats = nodes.map(n => n.lat);
      const lons = nodes.map(n => n.lon);

      const minLat = Math.min(...lats);
      const maxLat = Math.max(...lats);
      const minLon = Math.min(...lons);
      const maxLon = Math.max(...lons);

      const deltaLat = maxLat - minLat;
      const deltaLon = maxLon - minLon;
      const ar = deltaLon / deltaLat;
      const height = deltaLat * 111000 * 10;
      const width = height * ar * Math.cos(degToRad(maxLat));

      const points = [];
      const segments = [];
      for (const node of nodes) {
         const y = invLerp(maxLat, minLat, node.lat) * height;
         const x = invLerp(minLon, maxLon, node.lon) * width;
         const point = new Point(x, y);
         point.id = node.id;
         points.push(point);
      }

      const ways = data.elements.filter(w => w.type == "way");
      for (const way of ways) {
         const ids = way.nodes;
         for (let i = 1; i < ids.length; i++) {
            const prev = points.find((p) => p.id == ids[i - 1]);
            const cur = points.find((p) => p.id == ids[i]);
            const oneWay = way.tags.oneway || way.tags.lanes == 1;
            segments.push(new Segment(prev, cur, oneWay));
         }
      } 

      return { points, segments };
   }
}

// ───── world/js/markings/marking.js ─────
class Marking  {
   constructor(center, directionVector, width, height) {
      this.center = center;
      this.directionVector = directionVector;
      this.width = width;
      this.height = height;

      this.support = new Segment(
         translate(center, angle(directionVector), height / 2),
         translate(center, angle(directionVector), -height / 2)
      );
      this.poly = new Envelope(this.support, width, 0).poly;

      this.type = "marking";
   }

   static load(info) {
      const point = new Point(info.center.x, info.center.y);
      const dir = new Point(info.directionVector.x, info.directionVector.y);
      switch (info.type) {
         case "crossing":
            return new Crossing(point, dir, info.width, info.height);
         case "light":
            return new Light(point, dir, info.width, info.height);
         case "marking":
            return new Marking(point, dir, info.width, info.height);
         case "parking":
            return new Parking(point, dir, info.width, info.height);
         case "start":
            return new Start(point, dir, info.width, info.height);
         case "stop":
            return new Stop(point, dir, info.width, info.height);
         case "target":
            return new Target(point, dir, info.width, info.height);
         case "yield":
            return new Yield(point, dir, info.width, info.height);
      }
   }

   draw(ctx) {
      this.poly.draw(ctx);
   }
}

// ───── world/js/markings/stop.js ─────
class Stop extends Marking {
   constructor(center, directionVector, width, height) {
      super(center, directionVector, width, height);

      this.border = this.poly.segments[2];
      this.type = "stop";
   }

   draw(ctx) {
      this.border.draw(ctx, { width: 5, color: "white" });
      ctx.save();
      ctx.translate(this.center.x, this.center.y);
      ctx.rotate(angle(this.directionVector) - Math.PI / 2);
      ctx.scale(1, 3);

      ctx.beginPath();
      ctx.textBaseline = "middle";
      ctx.textAlign = "center";
      ctx.fillStyle = "white";
      ctx.font = "bold " + this.height * 0.3 + "px Arial";
      ctx.fillText("STOP", 0, 1);

      ctx.restore();
   }
}

// ───── world/js/markings/start.js ─────
class Start extends Marking {
   constructor(center, directionVector, width, height) {
      super(center, directionVector, width, height);

      this.type = "start";
      if (typeof document === "undefined") return;
      this.img = new Image();
      this.img.src = "car.png";
   }

   draw(ctx) {
      ctx.save();
      ctx.translate(this.center.x, this.center.y);
      ctx.rotate(angle(this.directionVector) - Math.PI / 2);
      
      ctx.drawImage(this.img, -this.img.width / 2, -this.img.height / 2);

      ctx.restore();
   }
}

// ───── world/js/markings/crossing.js ─────
class Crossing extends Marking {
   constructor(center, directionVector, width, height) {
      super(center, directionVector, width, height);

      this.borders = [this.poly.segments[0], this.poly.segments[2]];
      this.type = "crossing";
   }

   draw(ctx) {
      const perp = perpendicular(this.directionVector);
      const line = new Segment(
         add(this.center, scale(perp, this.width / 2)),
         add(this.center, scale(perp, -this.width / 2))
      );
      line.draw(ctx, {
         width: this.height,
         color: "white",
         dash: [11, 11]
      });
   }
}

// ───── world/js/markings/parking.js ─────
class Parking extends Marking {
   constructor(center, directionVector, width, height) {
      super(center, directionVector, width, height);

      this.borders = [this.poly.segments[0], this.poly.segments[2]];
      this.type = "parking";
   }

   draw(ctx) {
      for (const border of this.borders) {
         border.draw(ctx, { width: 5, color: "white" });
      }
      ctx.save();
      ctx.translate(this.center.x, this.center.y);
      ctx.rotate(angle(this.directionVector));

      ctx.beginPath();
      ctx.textBaseline = "middle";
      ctx.textAlign = "center";
      ctx.fillStyle = "white";
      ctx.font = "bold " + this.height * 0.9 + "px Arial";
      ctx.fillText("P", 0, 3);

      ctx.restore();
   }
}

// ───── world/js/markings/light.js ─────
class Light extends Marking {
   constructor(center, directionVector, width, height) {
      super(center, directionVector, width, 18);

      this.state = "off";
      this.border = this.poly.segments[0];
      this.type = "light";
   }

   draw(ctx) {
      const perp = perpendicular(this.directionVector);
      const line = new Segment(
         add(this.center, scale(perp, this.width / 2)),
         add(this.center, scale(perp, -this.width / 2))
      );

      const green = lerp2D(line.p1, line.p2, 0.2);
      const yellow = lerp2D(line.p1, line.p2, 0.5);
      const red = lerp2D(line.p1, line.p2, 0.8);

      new Segment(red, green).draw(ctx, {
         width: this.height,
         cap: "round"
      });

      green.draw(ctx, { size: this.height * 0.6, color: "#060" });
      yellow.draw(ctx, { size: this.height * 0.6, color: "#660" });
      red.draw(ctx, { size: this.height * 0.6, color: "#600" });

      switch (this.state) {
         case "green":
            green.draw(ctx, { size: this.height * 0.6, color: "#0F0" });
            break;
         case "yellow":
            yellow.draw(ctx, { size: this.height * 0.6, color: "#FF0" });
            break;
         case "red":
            red.draw(ctx, { size: this.height * 0.6, color: "#F00" });
            break;
      }
   }
}

// ───── world/js/markings/target.js ─────
class Target extends Marking {
   constructor(center, directionVector, width, height) {
      super(center, directionVector, width, height);
      this.type = "target";
   }

   draw(ctx) {
      this.center.draw(ctx, { color: "red", size: 30 });
      this.center.draw(ctx, { color: "white", size: 20 });
      this.center.draw(ctx, { color: "red", size: 10 });
   }
}

// ───── world/js/markings/yield.js ─────
class Yield extends Marking {
   constructor(center, directionVector, width, height) {
      super(center, directionVector, width, height);

      this.border = this.poly.segments[2];
      this.type = "yield";
   }

   draw(ctx) {
      this.border.draw(ctx, { width: 5, color: "white" });
      ctx.save();
      ctx.translate(this.center.x, this.center.y);
      ctx.rotate(angle(this.directionVector) - Math.PI / 2);
      ctx.scale(1, 3);

      ctx.beginPath();
      ctx.textBaseline = "middle";
      ctx.textAlign = "center";
      ctx.fillStyle = "white";
      ctx.font = "bold " + this.height * 0.3 + "px Arial";
      ctx.fillText("YIELD", 0, 1);

      ctx.restore();
   }
}

// ───── world/js/items/tree.js ─────
class Tree {
   constructor(center, size, height = 200) {
      this.center = center;
      this.size = size; // size of the base
      this.height = height;
      this.base = this.#generateLevel(center, size);
   }

   #generateLevel(point, size) {
      const points = [];
      const rad = size / 2;
      for (let a = 0; a < Math.PI * 2; a += Math.PI / 16) {
         const kindOfRandom = Math.cos(((a + this.center.x) * size) % 17) ** 2;
         const noisyRadius = rad * lerp(0.5, 1, kindOfRandom);
         points.push(translate(point, a, noisyRadius));
      }
      return new Polygon(points);
   }

   draw(ctx, viewPoint) {
      const top = getFake3dPoint(this.center, viewPoint, this.height);

      const levelCount = 7;
      for (let level = 0; level < levelCount; level++) {
         const t = level / (levelCount - 1);
         const point = lerp2D(this.center, top, t);
         const color = "rgb(30," + lerp(50, 200, t) + ",70)";
         const size = lerp(this.size, 40, t);
         const poly = this.#generateLevel(point, size);
         poly.draw(ctx, { fill: color, stroke: "rgba(0,0,0,0)" });
      }
   }
}

// ───── world/js/items/building.js ─────
class Building {
   constructor(poly, height = 200) {
      this.base = poly;
      this.height = height;
   }

   static load(info) {
      return new Building(Polygon.load(info.base), info.height);
   }

   draw(ctx, viewPoint) {
      const topPoints = this.base.points.map((p) =>
         getFake3dPoint(p, viewPoint, this.height * 0.6)
      );
      const ceiling = new Polygon(topPoints);

      const sides = [];
      for (let i = 0; i < this.base.points.length; i++) {
         const nextI = (i + 1) % this.base.points.length;
         const poly = new Polygon([
            this.base.points[i], this.base.points[nextI],
            topPoints[nextI], topPoints[i]
         ]);
         sides.push(poly);
      }
      sides.sort(
         (a, b) =>
            b.distanceToPoint(viewPoint) -
            a.distanceToPoint(viewPoint)
      );

      const baseMidpoints = [
         average(this.base.points[0], this.base.points[1]),
         average(this.base.points[2], this.base.points[3])
      ];

      const topMidpoints = baseMidpoints.map((p) =>
         getFake3dPoint(p, viewPoint, this.height)
      );

      const roofPolys = [
         new Polygon([
            ceiling.points[0], ceiling.points[3],
            topMidpoints[1], topMidpoints[0]
         ]),
         new Polygon([
            ceiling.points[2], ceiling.points[1],
            topMidpoints[0], topMidpoints[1]
         ])
      ];
      roofPolys.sort(
         (a, b) =>
            b.distanceToPoint(viewPoint) -
            a.distanceToPoint(viewPoint)
      );

      this.base.draw(ctx, { fill: "white", stroke: "rgba(0,0,0,0.2)", lineWidth: 20 });
      for (const side of sides) {
         side.draw(ctx, { fill: "white", stroke: "#AAA" });
      }
      ceiling.draw(ctx, { fill: "white", stroke: "white", lineWidth: 6 });
      for (const poly of roofPolys) {
         poly.draw(ctx, { fill: "#D44", stroke: "#C44", lineWidth: 8, join: "round" });
      }
   }
}

// ───── world/js/viewport.js ─────
class Viewport {
   constructor(canvas, zoom = 1, offset = null) {
      this.canvas = canvas;
      this.ctx = canvas.getContext("2d");

      this.zoom = zoom;
      this.center = new Point(canvas.width / 2, canvas.height / 2);
      this.offset = offset ? offset : scale(this.center, -1);

      this.drag = {
         start: new Point(0, 0),
         end: new Point(0, 0),
         offset: new Point(0, 0),
         active: false
      };

      this.#addEventListeners();
   }

   reset() {
      this.ctx.restore();
      this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
      this.ctx.save();
      this.ctx.translate(this.center.x, this.center.y);
      this.ctx.scale(1 / this.zoom, 1 / this.zoom);
      const offset = this.getOffset();
      this.ctx.translate(offset.x, offset.y);
   }

   getMouse(evt, subtractDragOffset = false) {
      const p = new Point(
         (evt.offsetX - this.center.x) * this.zoom - this.offset.x,
         (evt.offsetY - this.center.y) * this.zoom - this.offset.y
      );
      return subtractDragOffset ? subtract(p, this.drag.offset) : p;
   }

   getOffset() {
      return add(this.offset, this.drag.offset);
   }

   #addEventListeners() {
      this.canvas.addEventListener("mousewheel", this.#handleMouseWheel.bind(this));
      this.canvas.addEventListener("mousedown", this.#handleMouseDown.bind(this));
      this.canvas.addEventListener("mousemove", this.#handleMouseMove.bind(this));
      this.canvas.addEventListener("mouseup", this.#handleMouseUp.bind(this));
   }

   #handleMouseDown(evt) {
      if (evt.button == 1) { // middle button
         this.drag.start = this.getMouse(evt);
         this.drag.active = true;
      }
   }

   #handleMouseMove(evt) {
      if (this.drag.active) {
         this.drag.end = this.getMouse(evt);
         this.drag.offset = subtract(this.drag.end, this.drag.start);
      }
   }

   #handleMouseUp(evt) {
      if (this.drag.active) {
         this.offset = add(this.offset, this.drag.offset);
         this.drag = {
            start: new Point(0, 0),
            end: new Point(0, 0),
            offset: new Point(0, 0),
            active: false
         };
      }
   }

   #handleMouseWheel(evt) {
      const dir = Math.sign(evt.deltaY);
      const step = 0.1;
      this.zoom += dir * step;
      this.zoom = Math.max(1, Math.min(5, this.zoom));
   }
}

// ───── world/js/editors/markingEditor.js ─────
class MarkingEditor {
   constructor(viewport, world, targetSegments) {
      this.viewport = viewport;
      this.world = world;

      this.canvas = viewport.canvas;
      this.ctx = this.canvas.getContext("2d");

      this.mouse = null;
      this.intent = null;

      this.targetSegments = targetSegments;

      this.markings = world.markings;
   }

   // to be overwritten
   createMarking(center, directionVector) {
      return center;
   }

   enable() {
      this.#addEventListeners();
   }

   disable() {
      this.#removeEventListeners();
   }

   #addEventListeners() {
      this.boundMouseDown = this.#handleMouseDown.bind(this);
      this.boundMouseMove = this.#handleMouseMove.bind(this);
      this.boundContextMenu = (evt) => evt.preventDefault();
      this.canvas.addEventListener("mousedown", this.boundMouseDown);
      this.canvas.addEventListener("mousemove", this.boundMouseMove);
      this.canvas.addEventListener("contextmenu", this.boundContextMenu);
   }

   #removeEventListeners() {
      this.canvas.removeEventListener("mousedown", this.boundMouseDown);
      this.canvas.removeEventListener("mousemove", this.boundMouseMove);
      this.canvas.removeEventListener("contextmenu", this.boundContextMenu);
   }

   #handleMouseMove(evt) {
      this.mouse = this.viewport.getMouse(evt, true);
      const seg = getNearestSegment(
         this.mouse, 
         this.targetSegments, 
         10 * this.viewport.zoom
      );
      if (seg) {
         const proj = seg.projectPoint(this.mouse);
         if (proj.offset >= 0 && proj.offset <= 1) {
            this.intent = this.createMarking(
               proj.point,
               seg.directionVector()
            );
         } else {
            this.intent = null;
         }
      } else {
         this.intent = null;
      }
   }

   #handleMouseDown(evt) {
      if (evt.button == 0) { // left click
         if (this.intent) {
            this.markings.push(this.intent);
            this.intent = null;
         }
      }
      if (evt.button == 2) { // right click
         for (let i = 0; i < this.markings.length; i++) {
            const poly = this.markings[i].poly;
            if (poly.containsPoint(this.mouse)) {
               this.markings.splice(i, 1);
               return;
            }
         }
      }
   }

   display() {
      if (this.intent) {
         this.intent.draw(this.ctx);
      }
   }
}

// ───── world/js/editors/graphEditor.js ─────
class GraphEditor {
   constructor(viewport, graph) {
      this.viewport = viewport;
      this.canvas = viewport.canvas;
      this.graph = graph;

      this.ctx = this.canvas.getContext("2d");

      this.selected = null;
      this.hovered = null;
      this.dragging = false;
      this.mouse = null;
   }

   enable() {
      this.#addEventListeners();
   }

   disable() {
      this.#removeEventListeners();
      this.selected = false;
      this.hovered = false;
   }

   #addEventListeners() {
      this.boundMouseDown = this.#handleMouseDown.bind(this);
      this.boundMouseMove = this.#handleMouseMove.bind(this);
      this.boundMouseUp = () => this.dragging = false;
      this.boundContextMenu = (evt) => evt.preventDefault();
      this.canvas.addEventListener("mousedown", this.boundMouseDown);
      this.canvas.addEventListener("mousemove", this.boundMouseMove);
      this.canvas.addEventListener("mouseup", this.boundMouseUp);
      this.canvas.addEventListener("contextmenu", this.boundContextMenu);
   }

   #removeEventListeners() {
      this.canvas.removeEventListener("mousedown", this.boundMouseDown);
      this.canvas.removeEventListener("mousemove", this.boundMouseMove);
      this.canvas.removeEventListener("mouseup", this.boundMouseUp);
      this.canvas.removeEventListener("contextmenu", this.boundContextMenu);
   }

   #handleMouseMove(evt) {
      this.mouse = this.viewport.getMouse(evt, true);
      this.hovered = getNearestPoint(this.mouse, this.graph.points, 10 * this.viewport.zoom);
      if (this.dragging == true) {
         this.selected.x = this.mouse.x;
         this.selected.y = this.mouse.y;
      }
   }

   #handleMouseDown(evt) {
      if (evt.button == 2) { // right click
         if (this.selected) {
            this.selected = null;
         } else if (this.hovered) {
            this.#removePoint(this.hovered);
         }
      }
      if (evt.button == 0) { // left click
         if (this.hovered) {
            this.#select(this.hovered);
            this.dragging = true;
            return;
         }
         this.graph.addPoint(this.mouse);
         this.#select(this.mouse);
         this.hovered = this.mouse;
      }
   }

   #select(point) {
      if (this.selected) {
         this.graph.tryAddSegment(new Segment(this.selected, point));
      }
      this.selected = point;
   }

   #removePoint(point) {
      this.graph.removePoint(point);
      this.hovered = null;
      if (this.selected == point) {
         this.selected = null;
      }
   }

   dispose() {
      this.graph.dispose();
      this.selected = null;
      this.hovered = null;
   }

   display() {
      this.graph.draw(this.ctx);
      if (this.hovered) {
         this.hovered.draw(this.ctx, { fill: true });
      }
      if (this.selected) {
         const intent = this.hovered ? this.hovered : this.mouse;
         new Segment(this.selected, intent).draw(this.ctx, { dash: [3, 3] });
         this.selected.draw(this.ctx, { outline: true });
      }
   }
}

// ───── world/js/editors/crossingEditor.js ─────
class CrossingEditor extends MarkingEditor {
   constructor(viewport, world) {
      super(viewport, world, world.graph.segments);
   }

   createMarking(center, directionVector) {
      return new Crossing(
         center,
         directionVector,
         world.roadWidth,
         world.roadWidth / 2
      );
   }
}

// ───── world/js/editors/stopEditor.js ─────
class StopEditor extends MarkingEditor {
   constructor(viewport, world) {
      super(viewport, world, world.laneGuides);
   }

   createMarking(center, directionVector) {
      return new Stop(
         center,
         directionVector,
         world.roadWidth / 2,
         world.roadWidth / 2
      );
   }
}

// ───── world/js/editors/startEditor.js ─────
class StartEditor extends MarkingEditor {
   constructor(viewport, world) {
      super(viewport, world, world.laneGuides);
   }

   createMarking(center, directionVector) {
      return new Start(
         center,
         directionVector,
         world.roadWidth / 2,
         world.roadWidth / 2
      );
   }
}

// ───── world/js/editors/parkingEditor.js ─────
class ParkingEditor extends MarkingEditor {
   constructor(viewport, world) {
      super(viewport, world, world.laneGuides);
   }

   createMarking(center, directionVector) {
      return new Parking(
         center,
         directionVector,
         world.roadWidth / 2,
         world.roadWidth / 2
      );
   }
}

// ───── world/js/editors/lightEditor.js ─────
class LightEditor extends MarkingEditor {
   constructor(viewport, world) {
      super(viewport, world, world.laneGuides);
   }

   createMarking(center, directionVector) {
      return new Light(
         center,
         directionVector,
         world.roadWidth / 2,
         world.roadWidth / 2
      );
   }
}

// ───── world/js/editors/targetEditor.js ─────
class TargetEditor extends MarkingEditor {
   constructor(viewport, world) {
      super(viewport, world, world.laneGuides);
   }

   createMarking(center, directionVector) {
      return new Target(
         center,
         directionVector,
         world.roadWidth / 2,
         world.roadWidth / 2
      );
   }
}

// ───── world/js/editors/yieldEditor.js ─────
class YieldEditor extends MarkingEditor {
   constructor(viewport, world) {
      super(viewport, world, world.laneGuides);
   }

   createMarking(center, directionVector) {
      return new Yield(
         center,
         directionVector,
         world.roadWidth / 2,
         world.roadWidth / 2
      );
   }
}

// ───── world/js/world.js ─────
class World {
   constructor(
      graph,
      roadWidth = 100,
      roadRoundness = 10,
      buildingWidth = 150,
      buildingMinLength = 150,
      spacing = 50,
      treeSize = 160
   ) {
      this.graph = graph;
      this.roadWidth = roadWidth;
      this.roadRoundness = roadRoundness;
      this.buildingWidth = buildingWidth;
      this.buildingMinLength = buildingMinLength;
      this.spacing = spacing;
      this.treeSize = treeSize;

      this.envelopes = [];
      this.roadBorders = [];
      this.buildings = [];
      this.trees = [];
      this.laneGuides = [];

      this.markings = [];

      this.cars = [];
      this.bestCar = null;

      this.frameCount = 0;

      this.generate();
   }

   static load(info){
      const world = new World(new Graph());
      world.graph = Graph.load(info.graph);
      world.roadWidth = info.roadWidth;
      world.roadRoundness = info.roadRoundness;
      world.buildingWidth = info.buildingWidth;
      world.buildingMinLength = info.buildingMinLength;
      world.spacing = info.spacing;
      world.treeSize = info.treeSize;
      world.envelopes = info.envelopes.map((e) => Envelope.load(e));
      world.roadBorders = info.roadBorders.map((b) => new Segment(b.p1, b.p2));
      world.buildings = info.buildings.map((e) => Building.load(e));
      world.trees = info.trees.map((t) => new Tree(t.center, info.treeSize));
      world.laneGuides = info.laneGuides.map((g) => new Segment(g.p1, g.p2));
      world.markings = info.markings.map((m) => Marking.load(m));
      world.zoom = info.zoom;
      world.offset = info.offset;
      return world;
   }

   generate() {
      this.envelopes.length = 0;
      for (const seg of this.graph.segments) {
         this.envelopes.push(
            new Envelope(seg, this.roadWidth, this.roadRoundness)
         );
      }

      this.roadBorders = Polygon.union(this.envelopes.map((e) => e.poly));
      this.buildings = this.#generateBuildings();
      this.trees = this.#generateTrees();

      this.laneGuides.length = 0;
      this.laneGuides.push(...this.#generateLaneGuides());
   }

   #generateLaneGuides() {
      const tmpEnvelopes = [];
      for (const seg of this.graph.segments) {
         tmpEnvelopes.push(
            new Envelope(seg, this.roadWidth / 2, this.roadRoundness)
         );
      }
      const segments = Polygon.union(tmpEnvelopes.map((e) => e.poly));
      return segments;
   }

   #generateTrees() {
      const points = [
         ...this.roadBorders.map((s) => [s.p1, s.p2]).flat(),
         ...this.buildings.map((b) => b.base.points).flat(),
      ];
      const left = Math.min(...points.map((p) => p.x));
      const right = Math.max(...points.map((p) => p.x));
      const top = Math.min(...points.map((p) => p.y));
      const bottom = Math.max(...points.map((p) => p.y));

      const illegalPolys = [
         ...this.buildings.map((b) => b.base),
         ...this.envelopes.map((e) => e.poly),
      ];

      const trees = [];
      let tryCount = 0;
      while (tryCount < 100) {
         const p = new Point(
            lerp(left, right, Math.random()),
            lerp(bottom, top, Math.random())
         );

         // check if tree inside or nearby building / road
         let keep = true;
         for (const poly of illegalPolys) {
            if (
               poly.containsPoint(p) ||
               poly.distanceToPoint(p) < this.treeSize / 2
            ) {
               keep = false;
               break;
            }
         }

         // check if tree too close to other trees
         if (keep) {
            for (const tree of trees) {
               if (distance(tree.center, p) < this.treeSize) {
                  keep = false;
                  break;
               }
            }
         }

         // avoiding trees in the middle of nowhere
         if (keep) {
            let closeToSomething = false;
            for (const poly of illegalPolys) {
               if (poly.distanceToPoint(p) < this.treeSize * 2) {
                  closeToSomething = true;
                  break;
               }
            }
            keep = closeToSomething;
         }

         if (keep) {
            trees.push(new Tree(p, this.treeSize));
            tryCount = 0;
         }
         tryCount++;
      }
      return trees;
   }

   #generateBuildings() {
      const tmpEnvelopes = [];
      for (const seg of this.graph.segments) {
         tmpEnvelopes.push(
            new Envelope(
               seg,
               this.roadWidth + this.buildingWidth + this.spacing * 2,
               this.roadRoundness
            )
         );
      }

      const guides = Polygon.union(tmpEnvelopes.map((e) => e.poly));

      for (let i = 0; i < guides.length; i++) {
         const seg = guides[i];
         if (seg.length() < this.buildingMinLength) {
            guides.splice(i, 1);
            i--;
         }
      }

      const supports = [];
      for (let seg of guides) {
         const len = seg.length() + this.spacing;
         const buildingCount = Math.floor(
            len / (this.buildingMinLength + this.spacing)
         );
         const buildingLength = len / buildingCount - this.spacing;

         const dir = seg.directionVector();

         let q1 = seg.p1;
         let q2 = add(q1, scale(dir, buildingLength));
         supports.push(new Segment(q1, q2));

         for (let i = 2; i <= buildingCount; i++) {
            q1 = add(q2, scale(dir, this.spacing));
            q2 = add(q1, scale(dir, buildingLength));
            supports.push(new Segment(q1, q2));
         }
      }

      const bases = [];
      for (const seg of supports) {
         bases.push(new Envelope(seg, this.buildingWidth).poly);
      }

      const eps = 0.001;
      for (let i = 0; i < bases.length - 1; i++) {
         for (let j = i + 1; j < bases.length; j++) {
            if (
               bases[i].intersectsPoly(bases[j]) ||
               bases[i].distanceToPoly(bases[j]) < this.spacing - eps
            ) {
               bases.splice(j, 1);
               j--;
            }
         }
      }

      return bases.map((b) => new Building(b));
   }

   #getIntersections() {
      const subset = [];
      for (const point of this.graph.points) {
         let degree = 0;
         for (const seg of this.graph.segments) {
            if (seg.includes(point)) {
               degree++;
            }
         }

         if (degree > 2) {
            subset.push(point);
         }
      }
      return subset;
   }

   #updateLights() {
      const lights = this.markings.filter((m) => m instanceof Light);
      const controlCenters = [];
      for (const light of lights) {
         const point = getNearestPoint(light.center, this.#getIntersections());
         let controlCenter = controlCenters.find((c) => c.equals(point));
         if (!controlCenter) {
            controlCenter = new Point(point.x, point.y);
            controlCenter.lights = [light];
            controlCenters.push(controlCenter);
         } else {
            controlCenter.lights.push(light);
         }
      }
      const greenDuration = 2,
         yellowDuration = 1;
      for (const center of controlCenters) {
         center.ticks = center.lights.length * (greenDuration + yellowDuration);
      }
      const tick = Math.floor(this.frameCount / 60);
      for (const center of controlCenters) {
         const cTick = tick % center.ticks;
         const greenYellowIndex = Math.floor(
            cTick / (greenDuration + yellowDuration)
         );
         const greenYellowState =
            cTick % (greenDuration + yellowDuration) < greenDuration
               ? "green"
               : "yellow";
         for (let i = 0; i < center.lights.length; i++) {
            if (i == greenYellowIndex) {
               center.lights[i].state = greenYellowState;
            } else {
               center.lights[i].state = "red";
            }
         }
      }
      this.frameCount++;
   }

   draw(ctx, viewPoint, showStartMarkings = true, renderRadius = 1000) {
      this.#updateLights();

      for (const env of this.envelopes) {
         env.draw(ctx, { fill: "#BBB", stroke: "#BBB", lineWidth: 15 });
      }
      for (const marking of this.markings) {
         if (!(marking instanceof Start) || showStartMarkings) {
            marking.draw(ctx);
         }
      }
      for (const seg of this.graph.segments) {
         seg.draw(ctx, { color: "white", width: 4, dash: [10, 10] });
      }
      for (const seg of this.roadBorders) {
         seg.draw(ctx, { color: "white", width: 4 });
      }

      ctx.globalAlpha = 0.2;
      for (const car of this.cars) {
         car.draw(ctx);
      }
      ctx.globalAlpha = 1;
      if(this.bestCar) {
         this.bestCar.draw(ctx, true);
      }

      const items = [...this.buildings, ...this.trees].filter(
         (i) => i.base.distanceToPoint(viewPoint) < renderRadius
      );
      items.sort(
         (a, b) =>
            b.base.distanceToPoint(viewPoint) -
            a.base.distanceToPoint(viewPoint)
      );
      for (const item of items) {
         item.draw(ctx, viewPoint);
      }
   }
}

// ───── controls.js ─────
class Controls{
    constructor(type){
        this.forward=false;
        this.left=false;
        this.right=false;
        this.reverse=false;

        switch(type){
            case "KEYS":
                this.#addKeyboardListeners();
                break;
            case "DUMMY":
                this.forward=true;
                break;
        }
    }

    #addKeyboardListeners(){
        if(typeof document==="undefined"){return;}
        document.onkeydown=(event)=>{
            switch(event.key){
                case "ArrowLeft":
                    this.left=true;
                    break;
                case "ArrowRight":
                    this.right=true;
                    break;
                case "ArrowUp":
                    this.forward=true;
                    break;
                case "ArrowDown":
                    this.reverse=true;
                    break;
            }
        }
        document.onkeyup=(event)=>{
            switch(event.key){
                case "ArrowLeft":
                    this.left=false;
                    break;
                case "ArrowRight":
                    this.right=false;
                    break;
                case "ArrowUp":
                    this.forward=false;
                    break;
                case "ArrowDown":
                    this.reverse=false;
                    break;
            }
        }
    }
}

// ───── sensor.js ─────
class Sensor{
    constructor(car){
        this.car=car;
        this.rayCount=5;
        this.rayLength=150;
        this.raySpread=Math.PI/2;

        this.rays=[];
        this.readings=[];
    }

    update(roadBorders,traffic){
        this.#castRays();
        this.readings=[];
        for(let i=0;i<this.rays.length;i++){
            this.readings.push(
                this.#getReading(
                    this.rays[i],
                    roadBorders,
                    traffic
                )
            );
        }
    }

    #getReading(ray,roadBorders,traffic){
        let touches=[];

        for(let i=0;i<roadBorders.length;i++){
            const touch=getIntersection(
                ray[0],
                ray[1],
                roadBorders[i][0],
                roadBorders[i][1]
            );
            if(touch){
                touches.push(touch);
            }
        }

        for(let i=0;i<traffic.length;i++){
            const poly=traffic[i].polygon;
            for(let j=0;j<poly.length;j++){
                const value=getIntersection(
                    ray[0],
                    ray[1],
                    poly[j],
                    poly[(j+1)%poly.length]
                );
                if(value){
                    touches.push(value);
                }
            }
        }

        if(touches.length==0){
            return null;
        }else{
            const offsets=touches.map(e=>e.offset);
            const minOffset=Math.min(...offsets);
            return touches.find(e=>e.offset==minOffset);
        }
    }

    #castRays(){
        this.rays=[];
        for(let i=0;i<this.rayCount;i++){
            const rayAngle=lerp(
                this.raySpread/2,
                -this.raySpread/2,
                this.rayCount==1?0.5:i/(this.rayCount-1)
            )+this.car.angle;

            const start={x:this.car.x, y:this.car.y};
            const end={
                x:this.car.x-
                    Math.sin(rayAngle)*this.rayLength,
                y:this.car.y-
                    Math.cos(rayAngle)*this.rayLength
            };
            this.rays.push([start,end]);
        }
    }

    draw(ctx){
        for(let i=0;i<this.rayCount;i++){
            let end=this.rays[i][1];
            if(this.readings[i]){
                end=this.readings[i];
            }

            ctx.beginPath();
            ctx.lineWidth=2;
            ctx.strokeStyle="yellow";
            ctx.moveTo(
                this.rays[i][0].x,
                this.rays[i][0].y
            );
            ctx.lineTo(
                end.x,
                end.y
            );
            ctx.stroke();

            ctx.beginPath();
            ctx.lineWidth=2;
            ctx.strokeStyle="black";
            ctx.moveTo(
                this.rays[i][1].x,
                this.rays[i][1].y
            );
            ctx.lineTo(
                end.x,
                end.y
            );
            ctx.stroke();
        }
    }        
}

// ───── network.js ─────
class NeuralNetwork{
    constructor(neuronCounts){
        this.levels=[];
        for(let i=0;i<neuronCounts.length-1;i++){
            this.levels.push(new Level(
                neuronCounts[i],neuronCounts[i+1]
            ));
        }
    }

    static feedForward(givenInputs,network){
        let outputs=Level.feedForward(
            givenInputs,network.levels[0]);
        for(let i=1;i<network.levels.length;i++){
            outputs=Level.feedForward(
                outputs,network.levels[i]);
        }
        return outputs;
    }

    static mutate(network,amount=1){
        network.levels.forEach(level => {
            for(let i=0;i<level.biases.length;i++){
                level.biases[i]=lerp(
                    level.biases[i],
                    Math.random()*2-1,
                    amount
                )
            }
            for(let i=0;i<level.weights.length;i++){
                for(let j=0;j<level.weights[i].length;j++){
                    level.weights[i][j]=lerp(
                        level.weights[i][j],
                        Math.random()*2-1,
                        amount
                    )
                }
            }
        });
    }
}

class Level{
    constructor(inputCount,outputCount){
        this.inputs=new Array(inputCount);
        this.outputs=new Array(outputCount);
        this.biases=new Array(outputCount);

        this.weights=[];
        for(let i=0;i<inputCount;i++){
            this.weights[i]=new Array(outputCount);
        }

        Level.#randomize(this);
    }

    static #randomize(level){
        for(let i=0;i<level.inputs.length;i++){
            for(let j=0;j<level.outputs.length;j++){
                level.weights[i][j]=Math.random()*2-1;
            }
        }

        for(let i=0;i<level.biases.length;i++){
            level.biases[i]=Math.random()*2-1;
        }
    }

    static feedForward(givenInputs,level){
        for(let i=0;i<level.inputs.length;i++){
            level.inputs[i]=givenInputs[i];
        }

        for(let i=0;i<level.outputs.length;i++){
            let sum=0
            for(let j=0;j<level.inputs.length;j++){
                sum+=level.inputs[j]*level.weights[j][i];
            }

            if(sum>level.biases[i]){
                level.outputs[i]=1;
            }else{
                level.outputs[i]=0;
            } 
        }

        return level.outputs;
    }
}

// ───── car.js ─────
class Car{
    constructor(x,y,width,height,controlType,angle=0,maxSpeed=3,color="blue"){
        this.x=x;
        this.y=y;
        this.width=width;
        this.height=height;

        this.speed=0;
        this.acceleration=0.2;
        this.maxSpeed=maxSpeed;
        this.friction=0.05;
        this.angle=angle;
        this.damaged=false;

        this.fittness = 0;

        this.useBrain=controlType=="AI";

        if(controlType!="DUMMY"){
            this.sensor=new Sensor(this);
            this.brain=new NeuralNetwork(
                [this.sensor.rayCount,6,4]
            );
        }
        this.controls=new Controls(controlType);

        if(typeof document==="undefined"){return;}
        this.img=new Image();
        this.img.src="car.png"

        this.mask=document.createElement("canvas");
        this.mask.width=width;
        this.mask.height=height;

        const maskCtx=this.mask.getContext("2d");
        this.img.onload=()=>{
            maskCtx.fillStyle=color;
            maskCtx.rect(0,0,this.width,this.height);
            maskCtx.fill();

            maskCtx.globalCompositeOperation="destination-atop";
            maskCtx.drawImage(this.img,0,0,this.width,this.height);
        }
    }

    update(roadBorders,traffic){
        if(!this.damaged){
            this.#move();
            this.fittness += this.speed;
            this.polygon=this.#createPolygon();
            this.damaged=this.#assessDamage(roadBorders,traffic);
        }
        if(this.sensor){
            this.sensor.update(roadBorders,traffic);
            const offsets=this.sensor.readings.map(
                s=>s==null?0:1-s.offset
            );
            const outputs=NeuralNetwork.feedForward(offsets,this.brain);

            if(this.useBrain){
                this.controls.forward=outputs[0];
                this.controls.left=outputs[1];
                this.controls.right=outputs[2];
                this.controls.reverse=outputs[3];
            }
        }
    }

    #assessDamage(roadBorders,traffic){
        for(let i=0;i<roadBorders.length;i++){
            if(polysIntersect(this.polygon,roadBorders[i])){
                return true;
            }
        }
        for(let i=0;i<traffic.length;i++){
            if(polysIntersect(this.polygon,traffic[i].polygon)){
                return true;
            }
        }
        return false;
    }

    #createPolygon(){
        const points=[];
        const rad=Math.hypot(this.width,this.height)/2;
        const alpha=Math.atan2(this.width,this.height);
        points.push({
            x:this.x-Math.sin(this.angle-alpha)*rad,
            y:this.y-Math.cos(this.angle-alpha)*rad
        });
        points.push({
            x:this.x-Math.sin(this.angle+alpha)*rad,
            y:this.y-Math.cos(this.angle+alpha)*rad
        });
        points.push({
            x:this.x-Math.sin(Math.PI+this.angle-alpha)*rad,
            y:this.y-Math.cos(Math.PI+this.angle-alpha)*rad
        });
        points.push({
            x:this.x-Math.sin(Math.PI+this.angle+alpha)*rad,
            y:this.y-Math.cos(Math.PI+this.angle+alpha)*rad
        });
        return points;
    }

    #move(){
        if(this.controls.forward){
            this.speed+=this.acceleration;
        }
        if(this.controls.reverse){
            this.speed-=this.acceleration;
        }

        if(this.speed>this.maxSpeed){
            this.speed=this.maxSpeed;
        }
        if(this.speed<-this.maxSpeed/2){
            this.speed=-this.maxSpeed/2;
        }

        if(this.speed>0){
            this.speed-=this.friction;
        }
        if(this.speed<0){
            this.speed+=this.friction;
        }
        if(Math.abs(this.speed)<this.friction){
            this.speed=0;
        }

        if(this.speed!=0){
            const flip=this.speed>0?1:-1;
            if(this.controls.left){
                this.angle+=0.03*flip;
            }
            if(this.controls.right){
                this.angle-=0.03*flip;
            }
        }

        this.x-=Math.sin(this.angle)*this.speed;
        this.y-=Math.cos(this.angle)*this.speed;
    }

    draw(ctx,drawSensor=false){
        if(this.sensor && drawSensor){
            this.sensor.draw(ctx);
        }

        ctx.save();
        ctx.translate(this.x,this.y);
        ctx.rotate(-this.angle);
        if(!this.damaged){
            ctx.drawImage(this.mask,
                -this.width/2,
                -this.height/2,
                this.width,
                this.height);
            ctx.globalCompositeOperation="multiply";
        }
        ctx.drawImage(this.img,
            -this.width/2,
            -this.height/2,
            this.width,
            this.height);
        ctx.restore();

    }
}

// ───── visualizer.js ─────
class Visualizer{
    static drawNetwork(ctx,network){
        const margin=50;
        const left=margin;
        const top=margin;
        const width=ctx.canvas.width-margin*2;
        const height=ctx.canvas.height-margin*2;

        const levelHeight=height/network.levels.length;

        for(let i=network.levels.length-1;i>=0;i--){
            const levelTop=top+
                lerp(
                    height-levelHeight,
                    0,
                    network.levels.length==1
                        ?0.5
                        :i/(network.levels.length-1)
                );

            ctx.setLineDash([7,3]);
            Visualizer.drawLevel(ctx,network.levels[i],
                left,levelTop,
                width,levelHeight,
                i==network.levels.length-1
                    ?['🠉','🠈','🠊','🠋']
                    :[]
            );
        }
    }

    static drawLevel(ctx,level,left,top,width,height,outputLabels){
        const right=left+width;
        const bottom=top+height;

        const {inputs,outputs,weights,biases}=level;

        for(let i=0;i<inputs.length;i++){
            for(let j=0;j<outputs.length;j++){
                ctx.beginPath();
                ctx.moveTo(
                    Visualizer.#getNodeX(inputs,i,left,right),
                    bottom
                );
                ctx.lineTo(
                    Visualizer.#getNodeX(outputs,j,left,right),
                    top
                );
                ctx.lineWidth=2;
                ctx.strokeStyle=getRGBA(weights[i][j]);
                ctx.stroke();
            }
        }

        const nodeRadius=18;
        for(let i=0;i<inputs.length;i++){
            const x=Visualizer.#getNodeX(inputs,i,left,right);
            ctx.beginPath();
            ctx.arc(x,bottom,nodeRadius,0,Math.PI*2);
            ctx.fillStyle="black";
            ctx.fill();
            ctx.beginPath();
            ctx.arc(x,bottom,nodeRadius*0.6,0,Math.PI*2);
            ctx.fillStyle=getRGBA(inputs[i]);
            ctx.fill();
        }
        
        for(let i=0;i<outputs.length;i++){
            const x=Visualizer.#getNodeX(outputs,i,left,right);
            ctx.beginPath();
            ctx.arc(x,top,nodeRadius,0,Math.PI*2);
            ctx.fillStyle="black";
            ctx.fill();
            ctx.beginPath();
            ctx.arc(x,top,nodeRadius*0.6,0,Math.PI*2);
            ctx.fillStyle=getRGBA(outputs[i]);
            ctx.fill();

            ctx.beginPath();
            ctx.lineWidth=2;
            ctx.arc(x,top,nodeRadius*0.8,0,Math.PI*2);
            ctx.strokeStyle=getRGBA(biases[i]);
            ctx.setLineDash([3,3]);
            ctx.stroke();
            ctx.setLineDash([]);

            if(outputLabels[i]){
                ctx.beginPath();
                ctx.textAlign="center";
                ctx.textBaseline="middle";
                ctx.fillStyle="black";
                ctx.strokeStyle="white";
                ctx.font=(nodeRadius*1.5)+"px Arial";
                ctx.fillText(outputLabels[i],x,top+nodeRadius*0.1);
                ctx.lineWidth=0.5;
                ctx.strokeText(outputLabels[i],x,top+nodeRadius*0.1);
            }
        }
    }

    static #getNodeX(nodes,index,left,right){
        return lerp(
            left,
            right,
            nodes.length==1
                ?0.5
                :index/(nodes.length-1)
        );
    }
}

// ───── miniMap.js ─────
class MiniMap {
   constructor(canvas, graph, size) {
      this.canvas = canvas;
      this.graph = graph;
      this.size = size;

      canvas.width = size;
      canvas.height = size;
      this.ctx = canvas.getContext("2d");
   }

   update(viewPoint) {
      this.ctx.clearRect(0, 0, this.size, this.size);

      const scaler = 0.05;
      const scaledViewPoint = scale(viewPoint, -scaler);
      this.ctx.save();
      this.ctx.translate(
         scaledViewPoint.x + this.size / 2, 
         scaledViewPoint.y + this.size / 2
      );
      this.ctx.scale(scaler, scaler);
      for (const seg of this.graph.segments) {
         seg.draw(this.ctx, { width: 3 / scaler, color: "white" });
      }
      this.ctx.restore();
      new Point(this.size / 2, this.size / 2)
         .draw(this.ctx, { color: "blue", outline: true });
   }
}

export {
  Point, Segment, Polygon, Envelope, Graph, Osm,
  Marking, Stop, Start, Crossing, Parking, Light, Target, Yield,
  Tree, Building, Viewport,
  MarkingEditor, GraphEditor, CrossingEditor, StopEditor, StartEditor, ParkingEditor, LightEditor, TargetEditor, YieldEditor,
  World, Controls, Sensor, NeuralNetwork, Level, Car, Visualizer, MiniMap,
  getNearestPoint, getNearestSegment, distance, average, dot, add, subtract, scale, normalize, magnitude,
  perpendicular, translate, angle, getIntersection, lerp, lerp2D, invLerp, degToRad, getRandomColor, getFake3dPoint,
  polysIntersect, getRGBA,
};
