/**
 * Bundle gniziemazity/virtual-world (MIT, phase "11. MiniMap") into one ES module the app imports.
 *
 *   node scripts/build-vw.mjs [path-to-virtual-world-clone]
 *
 * The upstream files are plain browser globals loaded by <script> tags, so they are concatenated
 * in dependency order inside a single module scope and exported at the end. Only minimal patches
 * are applied (listed below); the algorithms are untouched.
 */
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(process.argv[2] ?? 'external/virtual-world/11. MiniMap');
const order = [
  'world/js/primitives/point.js',
  'world/js/primitives/segment.js',
  'world/js/primitives/polygon.js',
  'world/js/primitives/envelope.js',
  'world/js/math/utils.js',
  'utils.js',
  'world/js/math/graph.js',
  'world/js/math/osm.js',
  'world/js/markings/marking.js',
  'world/js/markings/stop.js',
  'world/js/markings/start.js',
  'world/js/markings/crossing.js',
  'world/js/markings/parking.js',
  'world/js/markings/light.js',
  'world/js/markings/target.js',
  'world/js/markings/yield.js',
  'world/js/items/tree.js',
  'world/js/items/building.js',
  'world/js/viewport.js',
  'world/js/editors/markingEditor.js',
  'world/js/editors/graphEditor.js',
  'world/js/editors/crossingEditor.js',
  'world/js/editors/stopEditor.js',
  'world/js/editors/startEditor.js',
  'world/js/editors/parkingEditor.js',
  'world/js/editors/lightEditor.js',
  'world/js/editors/targetEditor.js',
  'world/js/editors/yieldEditor.js',
  'world/js/world.js',
  'controls.js',
  'sensor.js',
  'network.js',
  'car.js',
  'visualizer.js',
  'miniMap.js',
];

function readSource(file) {
  const buf = fs.readFileSync(file);
  // world/js/math/utils.js is UTF-16 LE with a BOM upstream
  if (buf[0] === 0xff && buf[1] === 0xfe) return buf.toString('utf16le').replace(/^﻿/, '');
  return buf.toString('utf8').replace(/^﻿/, '');
}

const declared = new Set();
const parts = [];
for (const rel of order) {
  let src = readSource(path.join(root, rel)).replace(/\r\n/g, '\n');
  // Drop duplicate top-level function declarations (phase-1 utils.js repeats lerp/getIntersection/getRandomColor).
  src = src.replace(/^function\s+([A-Za-z_$][\w$]*)\s*\([^)]*\)\s*\{[\s\S]*?\n\}\n?/gm, (m, name) => {
    if (declared.has(name)) return `/* duplicate ${name} omitted */\n`;
    declared.add(name);
    return m;
  });
  parts.push(`// ───── ${rel} ─────\n${src.trim()}\n`);
}
let bundle = parts.join('\n');

// Patches (each must apply exactly once).
const patches = [
  // GraphEditor.display() draws with a page-global `ctx`; use the editor's own context.
  ["new Segment(this.selected, intent).draw(ctx, { dash: [3, 3] });", "new Segment(this.selected, intent).draw(this.ctx, { dash: [3, 3] });"],
  // Car builds an <img>/<canvas> for its 2D sprite; skip that outside a browser (tests) — the app renders cars itself.
  ["        this.img=new Image();\n        this.img.src=\"car.png\"\n\n        this.mask=document.createElement(\"canvas\");", "        if(typeof document===\"undefined\"){return;}\n        this.img=new Image();\n        this.img.src=\"car.png\"\n\n        this.mask=document.createElement(\"canvas\");"],
  // Start marking loads its sprite eagerly; same guard.
  ["      this.img = new Image();\n      this.img.src = \"car.png\";\n      this.type = \"start\";", "      this.type = \"start\";\n      if (typeof document === \"undefined\") return;\n      this.img = new Image();\n      this.img.src = \"car.png\";"],
];
for (const [from, to] of patches) {
  const n = bundle.split(from).length - 1;
  if (n !== 1) throw new Error(`patch expected once, found ${n}: ${from.slice(0, 60)}`);
  bundle = bundle.replace(from, to);
}

const header = `/* eslint-disable */
// @ts-nocheck
/**
 * virtual-world by Radu Mariescu-Istodor (https://github.com/gniziemazity/virtual-world), MIT License.
 * Generated by scripts/build-vw.mjs from phase "11. MiniMap" — do not edit by hand.
 *
 * The editors reference a page-global \`world\`; the host sets it with setEditorWorld().
 */
let world = null;
export function setEditorWorld(w) { world = w; }
`;
const footer = `
export {
  Point, Segment, Polygon, Envelope, Graph, Osm,
  Marking, Stop, Start, Crossing, Parking, Light, Target, Yield,
  Tree, Building, Viewport,
  MarkingEditor, GraphEditor, CrossingEditor, StopEditor, StartEditor, ParkingEditor, LightEditor, TargetEditor, YieldEditor,
  World, Controls, Sensor, NeuralNetwork, Level, Car, Visualizer, MiniMap,
  getNearestPoint, getNearestSegment, distance, average, dot, add, subtract, scale, normalize, magnitude,
  perpendicular, translate, angle, getIntersection, lerp, lerp2D, invLerp, degToRad, getRandomColor, getFake3dPoint,
  polysIntersect, getRGBA,
};
`;
fs.mkdirSync('src/vw', { recursive: true });
fs.writeFileSync('src/vw/virtual-world.js', header + bundle + footer);
console.log(`src/vw/virtual-world.js: ${(bundle.length / 1024).toFixed(0)} kB from ${order.length} files`);
